In [1]:
# Create Heatmaps for Weather Parameters

# For a basic heatmap, all we need to do is provide the following:
# - Latitudes and longitudes for the locations
# - A measurement value for each latitude and longitude in the form of arrays that have the same number of items in each array


# Import the dependencies.
import pandas as pd
import gmaps
import requests
# Import the API key.
from config import g_key

In [2]:
# Review use of dependencies
# - Pandas to read our CSV file and create the locations and measurements from the DataFrame. 
# - gmaps and the API key to create heatmaps and the locations map,
# - requests to make a request to the Google Places JSON file. 
# - allows us to get hotel locations from the latitude and longitude of the city.

# Read & store the CSV you saved created in part one into a DataFrame.
city_data_df = pd.read_csv("weather_data/cities.csv")
city_data_df.head()

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Nouadhibou,MR,2020-06-28 16:04:35,20.93,-17.03,77.00,61,0,24.16
1,1,Dikson,RU,2020-06-28 16:06:20,73.51,80.55,43.97,100,100,9.04
2,2,Aksu,CN,2020-06-28 16:06:21,41.12,80.26,71.13,33,100,4.83
3,3,Lavrentiya,RU,2020-06-28 16:04:33,65.58,-171.00,38.88,81,41,9.24
4,4,Tornio,FI,2020-06-28 16:06:21,65.85,24.15,66.20,48,1,6.93

In [3]:
# caveat to using gmaps: The data we use for any mapping must be either an integer or a floating-point decimal number. 
city_data_df.dtypes

City_ID         int64
City           object
Country        object
Date           object
Lat           float64
Lng           float64
Max Temp      float64
Humidity        int64
Cloudiness      int64
Wind Speed    float64
dtype: object

In [4]:
# Create a Maximum Temperature Heatmap

# Tell gmaps to use your API key. Configure gmaps to use your API key needed only once.
# Configure gmaps to use your Google API key.
gmaps.configure(api_key=g_key)

# Google heatmaps do not plot negative numbers. If you have a maximum temperature that is less than 0 °F, then you will get an InvalidWeightException error for this line of code:
# heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Replace temps with our code for the list comprehension so our heat_layer code looks like the following:
#heat_layer = gmaps.heatmap_layer(locations,weights=[max(temp, 0) for temp in max_temp])

In [5]:
# Heatmap of temperature

# Get the latitude and longitude as an array of latitude and longitude pairs.
locations = city_data_df[["Lat", "Lng"]]
# Get the maximum temperature.
max_temp = city_data_df["Max Temp"]
# 3. Assign the figure variable to the gmaps.figure() attribute.
fig = gmaps.figure()
# 4. Assign the heatmap_layer variable to the heatmap_layer attribute and add in the locations.
# heat_layer = gmaps.heatmap_layer(locations, weights=max_temp)
# Dissipation option for creating heatmaps .heat_layer()attribute.
# - Default option for the dissipation is “True,” so we need to set our “dissipation” to “False.”
# - max_intensity make each measurement have a better gradient variance.
# - point_radius make each measurement radius larger.
heat_layer = gmaps.heatmap_layer(locations, 
                                 weights=[max(temp, 0) for temp in max_temp], 
                                 dissipating=False, 
                                 max_intensity=300, 
                                 point_radius=4)

# Adjust Heatmap Zoom, Intensity, and Point Radius
# - add the geographic center of Earth in the form of latitude and longitude (30.0° N and 31.0° E). 
# - add a zoom level so that only one map of Earth is shown.

fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)

# 5. Add the heatmap layer.
fig.add_layer(heat_layer)

# 6. Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [6]:
# Create a Percent Humidity Heatmap

# Heatmap of percent humidity
locations = city_data_df[["Lat", "Lng"]]
humidity = city_data_df["Humidity"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(
    locations, 
    weights=humidity, 
    dissipating=False, 
    max_intensity=300, 
    point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [ ]:
# Create a Percent Cloudiness Heatmap

# Heatmap of percent cloudiness
locations = city_data_df[["Lat", "Lng"]]
clouds = city_data_df["Cloudiness"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(
    locations, 
    weights=clouds, 
    dissipating=False, 
    max_intensity=300, 
    point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

In [7]:
# Create a Wind Speed Heatmap

# Heatmap of percent Wind Speed
locations = city_data_df[["Lat", "Lng"]]
wind = city_data_df["Wind Speed"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(
    locations, 
    weights=wind, 
    dissipating=False, 
    max_intensity=300, 
    point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [8]:
# Ask the customer to add a minimum and maximum temperature value.
min_temp = float(input("What is the minimum temperature you would like for your trip? "))
max_temp = float(input("What is the maximum temperature you would like for your trip? "))

What is the minimum temperature you would like for your trip? 75
What is the maximum temperature you would like for your trip? 90

In [9]:
# Filter the dataset to find the cities that fit the criteria.
preferred_cities_df = city_data_df.loc[(city_data_df["Max Temp"] <= max_temp) & \
                                       (city_data_df["Max Temp"] >= min_temp)]
preferred_cities_df.head(10)

,City_ID,City,Country,Date,Lat,Lng,Max Temp,Humidity,Cloudiness,Wind Speed
0,0,Nouadhibou,MR,2020-06-28 16:04:35,20.93,-17.03,77.00,61,0,24.16
11,11,Weligama,LK,2020-06-28 16:06:22,5.97,80.42,80.98,85,83,10.27
13,13,Carmen,MX,2020-06-28 16:03:51,18.63,-91.83,82.40,78,40,14.99
18,18,Kailua,US,2020-06-28 16:06:23,21.40,-157.74,75.20,73,40,4.70
24,24,Kavieng,PG,2020-06-28 16:06:23,-2.57,150.80,82.53,79,35,12.33
30,30,Jacqueville,CI,2020-06-28 16:06:24,5.21,-4.41,77.00,88,20,11.41
36,36,Cedar City,US,2020-06-28 16:03:37,37.68,-113.06,78.80,22,1,24.16
39,39,Itarema,BR,2020-06-28 16:04:21,-2.92,-39.92,86.09,61,25,13.82
41,41,Hot Springs,US,2020-06-28 16:03:00,34.50,-93.06,84.20,66,75,8.05
42,42,Shangqiu,CN,2020-06-28 16:06:25,34.45,115.65,75.00,85,100,1.99

In [10]:
preferred_cities_df.count()

City_ID       228
City          228
Country       226
Date          228
Lat           228
Lng           228
Max Temp      228
Humidity      228
Cloudiness    228
Wind Speed    228
dtype: int64

In [11]:
preferred_cities_df.notnull().sum()

City_ID       228
City          228
Country       226
Date          228
Lat           228
Lng           228
Max Temp      228
Humidity      228
Cloudiness    228
Wind Speed    228
dtype: int64

In [ ]:
# Consider the following guidance:
# Depending on the time of year and the seasons, might have to adjust the minimum and maximum temperature to get enough cities.
# Keep the number of cities to fewer than 200, makes it easier to plot the markers on the heatmap.
# If you have rows with null values, drop them using the dropna() method at the end of filtering statement when creating the new DataFrame.

In [12]:
# Map Vacation Criteria

# Once customers filtered the database (DataFrame) based on their temperature preferences, 
# - show them a heatmap for the maximum temperature for the filtered cities. 
# - Create a marker for each city that will display 
# - name of the city, 
# - country code, 
# - maximum temperature, and 
# - name of a nearby hotel within three miles of the coordinates when the marker is clicked.

# Using the coordinates from the preferred_cities_df DataFrame, 
# - find a hotel using our Google Places API
# - retrieve that hotel information. 
# - store it for reference, add the information to the pop-up marker.

# Make a copy of the preferred_cities_df DataFrame and name it hotel_df. 
# For the hotel_df, keep the columns “City,” “Country,” “Max Temp,” “Lat,” and “Lng.” 
# Add a new column to the hotel_df DataFrame to hold the name of the hotel.

# Create DataFrame called hotel_df to store hotel names along with city, country, max temp, and coordinates.
hotel_df = preferred_cities_df[["City", "Country", "Max Temp", "Lat", "Lng"]].copy()
hotel_df["Hotel Name"] = ""
hotel_df.head(10)

           City Country  Max Temp    Lat     Lng Hotel Name
0    Nouadhibou      MR     77.00  20.93  -17.03
11     Weligama      LK     80.98   5.97   80.42
13       Carmen      MX     82.40  18.63  -91.83
18       Kailua      US     75.20  21.40 -157.74
24      Kavieng      PG     82.53  -2.57  150.80
30  Jacqueville      CI     77.00   5.21   -4.41
36   Cedar City      US     78.80  37.68 -113.06
39      Itarema      BR     86.09  -2.92  -39.92
41  Hot Springs      US     84.20  34.50  -93.06
42     Shangqiu      CN     75.00  34.45  115.65

In [13]:
# Retrieve Hotels from a Nearby Search
# Set the parameters for the search.
# - use the Google Places Nearby Search request to find the nearest establishment to geographic coordinates
# Specific parameters include:
# - Our API key
# - A location, which will be the latitude and longitude
# - A radius for the search. The radius can be up to 50,000 meters or approximately 31 miles. This distance is much too great for finding hotels, 
# - we’ll keep our search to 5,000 meters.
# - If we use rankby=distance parameter, need to add one or more of the three parameters above. 
# - We won’t use rankby=distance because, we will search based on the radius from a given latitude and longitude.
#
# Use these parameters:
# - API key
# - Latitude and longitude
# - 5,000-meter radius
# - Type of place

# Set parameters to search for a hotel.
params = {
    "radius": 5000,
    "type": "lodging",
    "key": g_key
}

In [14]:
# Iterate through hotel_df DataFrame
# Use iterrows() function to perform the iteration; 
# provide the index and the row in the for loop
# - for index, row in df.iterrows().

# Iterate through the DataFrame.
for index, row in hotel_df.iterrows():
    # Get the latitude and longitude.
    lat = row["Lat"]
    lng = row["Lng"]

    # Add the latitude and longitude to location key for the params dictionary.
    params["location"] = f"{lat},{lng}"

    # Use the search term: "lodging" and our latitude and longitude.
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    # Make request and get the JSON data from the search.
    hotels = requests.get(base_url, params=params).json()
    # Grab the first hotel from the results and store the name.
    #hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    try:
        hotel_df.loc[index, "Hotel Name"] = hotels["results"][0]["name"]
    except (IndexError):
        print("Hotel not found... skipping.")
    # If you encounter more errors, add them to the except block—like so, (IndexError, NewError)—and continue running your code until there are no errors.

Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.
Hotel not found... skipping.

In [15]:
hotel_df

,City,Country,Max Temp,Lat,Lng,Hotel Name
0,Nouadhibou,MR,77.00,20.93,-17.03,El Medina
11,Weligama,LK,80.98,5.97,80.42,Weligama Bay Resort
13,Carmen,MX,82.40,18.63,-91.83,Hotel Lossandes
18,Kailua,US,75.20,21.40,-157.74,Sheffield House Bed & Breakfast
24,Kavieng,PG,82.53,-2.57,150.80,Nusa Island Retreat
...,...,...,...,...,...,...
563,Sao Jose Da Coroa Grande,BR,78.75,-8.90,-35.15,Crôa Mares Hotel
564,Avera,US,89.60,33.19,-82.53,
565,Sabzevar,IR,78.60,36.21,57.68,پارکینگ وسایل سنگین جنوب
566,Praid,RO,84.20,46.55,25.13,Hotel Praid
567,Barinas,VE,85.39,8.62,-70.21,Hotel Suites Mastranto

In [16]:
# Create a Maximum Temperature Heatmap from a Hotel DataFrame

# Add a heatmap of temperature for the vacation spots.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, dissipating=False,
             max_intensity=300, point_radius=4)

fig.add_layer(heat_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [17]:
# Add a heatmap of temperature for the vacation spots and marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp, 
             dissipating=False, max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)
# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))

In [19]:
# Add popup marker for each city

info_box_template = """
<dl>
<dt>Hotel Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
<dt>Max Temp</dt><dd>{Max Temp} °F</dd>
</dl>
"""

# Store the DataFrame Row.
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]

In [20]:
# Add a heatmap of temperature for the vacation spots and a pop-up marker for each city.
locations = hotel_df[["Lat", "Lng"]]
max_temp = hotel_df["Max Temp"]
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
heat_layer = gmaps.heatmap_layer(locations, weights=max_temp,dissipating=False,
             max_intensity=300, point_radius=4)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(heat_layer)
fig.add_layer(marker_layer)

# Call the figure to plot the data.
fig

Figure(layout=FigureLayout(height='420px'))